### ISSUE TITLE
Add parent_collection_ids (maybe?)

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/hydra-pcdm#157]
It's used in hydra-collections in the Collectible class, so it may have some utility. It would at least be good for consistency.

**Comment by jcoyne** [comment]
It's also used in CurationConcerns::GenericWorkActor, so probably worth doing.

**Comment by grosscol** [comment]
This would be added to the GenericWorks and GenericCollections models?

**Comment by mjgiarlo** [comment]
@terrellt is this on your plate?  @blancoj might like to take a crack at it if you haven't already started this work.

**Comment by terrellt** [comment]
@mjgiarlo I intended to take a look, but won't be able to until tomorrow. @blancoj is welcome to do it. Maybe has_many can take care of it?

**Comment by terrellt** [comment]
@blancoj I think this is closed.

**Comment by blancoj** [comment]
@terrellt yes.  Do I need to do anything?
